apiVersion: apps/v1
kind: Deployment
metadata:
  name:  asif2023
  namespace: demo
spec:
  selector:
    matchLabels:
      app: asif2023
  template:
    metadata:
      labels:
        app: asif2023
    spec:
      containers:
        - name: asif2023
          image: asif1988/scum-dhaka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000